baseURL = "https://tb5z035i.github.io/blog/"
languageCode = "en-us"
title = "My Blog"
theme = "terminal"
[pagination]
  pagerSize = 5

[params]
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true
  themeColor = "green"
  showLastUpdated = false
  contentTypeName = "posts"

  # Giscus comment system -- fill in after setup at https://giscus.app
  [params.giscus]
    repo = "tb5z035i/blog"
    repoId = "R_kgDORSxh1A"
    category = "Announcements"
    categoryId = "DIC_kwDORSxh1M4C2smu"
    mapping = "pathname"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    theme = "transparent_dark"
    lang = "en"

[languages]
  [languages.en]
    languageName = "English"
    title = "My Blog"

    [[languages.en.menu.main]]
      name = "Home"
      url = "/"
      weight = 1

    [[languages.en.menu.main]]
      name = "Posts"
      url = "/posts"
      weight = 2
